Include a new requirements for development and tests
chaoss/grimoirelab-perceval-mozilla pull request #64
Opened 2022-05-26 10:21 UTC by jjmerchante

Using Poetry by default install the latest version of the package from PyPI.

This PR includes a new file necessary for development and testing. 

After `poetry install` you can run `poetry run pip install -r requirements.txt` and it will
install the latest version available in the master branch of the GrimoireLab repositories.

2022-05-26 10:58 UTC, sduenas requested changes
LGTM just change the changelog title. In general, I think changelogs shouldn't start with a verb because it will be implicit in the type of change. I think it's better to have a name for the functionality added/removed.

2022-05-26 10:58 UTC, sduenas commented on releases/unreleased/include-requirements-for-development.yml
> +title: Include dependencies file for development
```suggestion
title: Dependencies file for development
```

2022-05-27 06:09 UTC, vchrombie commented
Thanks for opening the PR @jjmerchante.

I have a workaround for this and thought of taking your input. Since we have poetry support, we can address the problem using it. 

For reference, I use the https://github.com/vchrombie/grimoirelab-perceval-zulip/blob/master/pyproject.toml

```toml
[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.7.0"

# grimoirelab dependencies
grimoirelab-toolkit = "*"
perceval = "*"

[tool.poetry.dev-dependencies]
httpretty = "1.0.2"
flake8 = "^3.9.2"
coverage = "^5.5"

# grimoirelab dependencies
grimoirelab-toolkit = {git = "https://github.com/chaoss/grimoirelab-toolkit.git", rev = "master"}
perceval = {git = "https://github.com/chaoss/grimoirelab-perceval.git", rev = "master"}
```

With this, `poetry install` would install all the dependencies (`tool.poetry.dependencies` + `tool.poetry.dev-dependencies`) and if a dependency is mentioned in two categories, it will use the version in dev-dependencies. At the same time, `poetry build` will only use the `tool.poetry.dependencies`. I think this is what we are trying to aim for, please correct me if I'm wrong. This way we can get rid of any sort of requirements txt files.

Please let me know if you have any comments @sduenas.

2022-05-27 07:03 UTC, jjmerchante commented
Yes, I really like that idea. But we have another problem when using the master branch with Poetry:

When one repository (grimoire-elk) depends on another (perceval), Poetry stores the exact commit it depends on in `poetry.lock` and does not use the master branch when installing it. If a new commit is added to Perceval, all repositories that depend on it must be updated (`poetry update perceval`) to use the latest commit.

2022-05-27 09:00 UTC, sduenas commented
@vchrombie I think we should go with the proposal of @jjmerchante . We need a way to test everything with the latest changes of the platform for developing purposes, at the same time that we have fixed versions for the packages for production/stable environments.
I know @jjmerchante proposal is not ideal but poetry doesn't help either. If there were a way to tell poetry that we want these pypi packages for a stable release and these others for development, that will be great but right now, it's impossible and I don't think it's going to change in the near future.

@vchrombie do you have any other idea?

2022-05-27 10:10 UTC, vchrombie commented
Hi @jjmerchante @sduenas, thanks for your comments. I went through your comments and I understand the conerns.

> @vchrombie I think we should go with the proposal of @jjmerchante . We need a way to test everything with the latest changes of the platform for developing purposes, at the same time that we have fixed versions for the packages for production/stable environments.

I agree with you, let's go ahead with this. :+1:

2022-05-27 10:38 UTC, sduenas approved these changes
LGTM

2022-05-27 10:55 UTC, closed without merging

2022-05-27 10:57 UTC, sduenas commented
Merged!